name: textlint

on:
  pull_request:
    paths:
    - '_i18n/ja/_posts/**'

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install
      run: yarn install
    - name: textlint reviewdog
      uses: tsuyoshicho/action-textlint@v3
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        textlint_flags: "_i18n/ja/_posts/**"
